public enum ResourceBase
{
	Mana = 0,
	AllBuildingsProfit = 1,
	PPS = 2,
	SoulPower = 3,
	Souls = 4,
	Ascends = 5,
	IdleTime = 6,
	IdleBonus = 7,
	ManaTotal = 8,
	ManaAllTime = 9,
	OfflineProduction = 10,
	TotalBuildings = 11,
	TotalUpgrades = 12,
	PlayedTime = 13,
	PlayedTimeRealm = 14,
	PlayedTimeTotal = 15,
	OfflineTimeTotal = 16,
	IdleTimeSession = 17,
	IdleTimeTotal = 18,
	IdleSaveClicks = 19,
	IdleSaveClicksCD = 20,
	GCatBonus = 21,
	BCatBonus = 22,
	IdleOfflineBonus = 23,
	SplinterIncome = 24
}
