#!/usr/bin/env python3
"""
Generate calculator-side source files from verified Idle Wizard engine maps.

Input:
  iw_workspace_vNext/engine_maps/*.json
  iw_workspace_vNext/raw_files/**/*.bytes.txt

Output:
  src/IdleWizard.BuildTool.Core/Generated/
    GameEffectName.generated.cs
    ResourceKeyCatalog.generated.cs
    DataFileCatalog.generated.cs

  iw_workspace_vNext/generated_reports/
    data_schemas.json
    generation_summary.json

Rules:
- Use only generated engine maps and actual data files.
- Do not infer formulas.
- Generate catalogs/enums only.
"""

from __future__ import annotations

import argparse
import json
import keyword
import re
from pathlib import Path
from typing import Any


CS_RESERVED = {
    "abstract", "as", "base", "bool", "break", "byte", "case", "catch",
    "char", "checked", "class", "const", "continue", "decimal", "default",
    "delegate", "do", "double", "else", "enum", "event", "explicit",
    "extern", "false", "finally", "fixed", "float", "for", "foreach",
    "goto", "if", "implicit", "in", "int", "interface", "internal", "is",
    "lock", "long", "namespace", "new", "null", "object", "operator",
    "out", "override", "params", "private", "protected", "public",
    "readonly", "ref", "return", "sbyte", "sealed", "short", "sizeof",
    "stackalloc", "static", "string", "struct", "switch", "this", "throw",
    "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe",
    "ushort", "using", "virtual", "void", "volatile", "while",
}


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def cs_identifier(value: str, fallback_prefix: str = "Value") -> str:
    value = value.strip()

    if not value:
        return fallback_prefix

    # Split on non-alphanumeric characters.
    parts = re.split(r"[^A-Za-z0-9]+", value)
    parts = [p for p in parts if p]

    if not parts:
        ident = fallback_prefix
    else:
        ident = "".join(p[:1].upper() + p[1:] for p in parts)

    if not ident:
        ident = fallback_prefix

    if ident[0].isdigit():
        ident = f"{fallback_prefix}{ident}"

    if ident in CS_RESERVED:
        ident = f"{ident}_"

    return ident


def cs_string(value: str) -> str:
    return (
        value
        .replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\r", "\\r")
        .replace("\n", "\\n")
    )


def generate_effect_enum(engine_maps: Path, out_dir: Path) -> dict:
    effect_names_path = engine_maps / "effect_names.json"
    effect_names = load_json(effect_names_path)

    values = []

    if effect_names.get("enums"):
        values = effect_names["enums"][0].get("values", [])

    lines = []
    lines.append("// <auto-generated />")
    lines.append("namespace IdleWizard.BuildTool.Core.Generated;")
    lines.append("")
    lines.append("/// <summary>")
    lines.append("/// Generated from EffectNames.cs via iw_generate_calculator_sources.py.")
    lines.append("/// This is a source-backed catalog, not a hand-written formula implementation.")
    lines.append("/// </summary>")
    lines.append("public enum GameEffectName")
    lines.append("{")

    used = set()

    for index, item in enumerate(values):
        raw_name = str(item.get("name", ""))
        raw_value = str(item.get("value", index))

        enum_name = cs_identifier(raw_name, "Effect")

        original_enum_name = enum_name
        suffix = 2

        while enum_name in used:
            enum_name = f"{original_enum_name}{suffix}"
            suffix += 1

        used.add(enum_name)

        if re.fullmatch(r"-?\d+", raw_value):
            lines.append(f"    {enum_name} = {raw_value},")
        else:
            lines.append(f"    {enum_name},")

    lines.append("}")

    output = out_dir / "GameEffectName.generated.cs"
    write_text(output, "\n".join(lines) + "\n")

    return {
        "file": str(output),
        "effect_count": len(values),
    }


def extract_resource_candidates(engine_maps: Path) -> list[str]:
    resources_path = engine_maps / "game_context_resources.json"
    resources = load_json(resources_path)

    candidates = set()

    for hit in resources.get("resource_registration_like_calls", []):
        for literal in hit.get("string_literals", []):
            literal = str(literal).strip()

            if not literal:
                continue

            # Keep likely keys, avoid obvious prose.
            if any(x in literal for x in [".", ":", "/", "_"]):
                candidates.add(literal)

        for arg in hit.get("args", []):
            arg = str(arg).strip()

            # Extract quoted strings from args too.
            for literal in re.findall(r'"([^"\\]*(?:\\.[^"\\]*)*)"', arg):
                if any(x in literal for x in [".", ":", "/", "_"]):
                    candidates.add(literal)

    return sorted(candidates)


def generate_resource_catalog(engine_maps: Path, out_dir: Path) -> dict:
    keys = extract_resource_candidates(engine_maps)

    lines = []
    lines.append("// <auto-generated />")
    lines.append("namespace IdleWizard.BuildTool.Core.Generated;")
    lines.append("")
    lines.append("/// <summary>")
    lines.append("/// Generated resource-key candidates discovered from GameContext/GameManager/manager source.")
    lines.append("/// These are candidates only; the evaluator must still register supported keys explicitly.")
    lines.append("/// </summary>")
    lines.append("public static class ResourceKeyCatalog")
    lines.append("{")

    used = set()

    for key in keys:
        name = cs_identifier(key, "Key")
        original_name = name
        suffix = 2

        while name in used:
            name = f"{original_name}{suffix}"
            suffix += 1

        used.add(name)
        lines.append(f'    public const string {name} = "{cs_string(key)}";')

    lines.append("")
    lines.append("    public static readonly string[] All =")
    lines.append("    [")
    for key in keys:
        lines.append(f'        "{cs_string(key)}",')
    lines.append("    ];")
    lines.append("}")

    output = out_dir / "ResourceKeyCatalog.generated.cs"
    write_text(output, "\n".join(lines) + "\n")

    return {
        "file": str(output),
        "resource_key_candidate_count": len(keys),
    }


def infer_schema_from_value(value: Any, depth: int = 0) -> Any:
    if depth > 3:
        return type(value).__name__

    if isinstance(value, dict):
        return {
            str(k): infer_schema_from_value(v, depth + 1)
            for k, v in list(value.items())[:200]
        }

    if isinstance(value, list):
        if not value:
            return []

        # Merge object keys from first several items.
        if all(isinstance(x, dict) for x in value[:20]):
            merged = {}

            for item in value[:20]:
                for key, sub_value in item.items():
                    merged.setdefault(str(key), infer_schema_from_value(sub_value, depth + 1))

            return [merged]

        return [infer_schema_from_value(value[0], depth + 1)]

    if value is None:
        return "null"

    if isinstance(value, bool):
        return "bool"

    if isinstance(value, int):
        return "int"

    if isinstance(value, float):
        return "float"

    if isinstance(value, str):
        return "string"

    return type(value).__name__


def infer_data_schemas(workspace: Path, reports_dir: Path) -> dict:
    raw = workspace / "raw_files"

    schemas = []

    data_paths = []
    data_paths.extend(sorted(list(raw.rglob("*.bytes")) + list(raw.rglob("*.bytes.txt"))))
    data_paths.extend(sorted(raw.rglob("*.json")))

    for path in data_paths:
        relative = str(path.relative_to(raw))
        text = path.read_text(errors="ignore")
        stripped = text.lstrip()

        entry = {
            "file": relative,
            "size": path.stat().st_size,
            "looks_json": stripped.startswith(("{", "[")),
            "parse_status": "not_json",
            "schema": None,
        }

        if stripped.startswith(("{", "[")):
            try:
                parsed = json.loads(text)
                entry["parse_status"] = "parsed"
                entry["schema"] = infer_schema_from_value(parsed)
            except Exception as exc:
                entry["parse_status"] = "parse_error"
                entry["error"] = str(exc)

        schemas.append(entry)

    report = {
        "data_file_count": len(schemas),
        "files": schemas,
    }

    output = reports_dir / "data_schemas.json"
    write_text(output, json.dumps(report, indent=2))

    return {
        "file": str(output),
        "data_file_count": len(schemas),
        "json_parsed_count": sum(1 for x in schemas if x["parse_status"] == "parsed"),
    }


def generate_data_file_catalog(workspace: Path, out_dir: Path) -> dict:
    raw = workspace / "raw_files"

    files = []

    for path in sorted(raw.rglob("*")):
        if path.is_file() and (
            (path.name.endswith(".bytes") or path.name.endswith(".bytes.txt"))
            or path.suffix == ".json"
        ):
            files.append(str(path.relative_to(raw)).replace("\\", "/"))

    lines = []
    lines.append("// <auto-generated />")
    lines.append("namespace IdleWizard.BuildTool.Core.Generated;")
    lines.append("")
    lines.append("public static class DataFileCatalog")
    lines.append("{")
    lines.append("    public static readonly string[] All =")
    lines.append("    [")
    for file in files:
        lines.append(f'        "{cs_string(file)}",')
    lines.append("    ];")
    lines.append("}")

    output = out_dir / "DataFileCatalog.generated.cs"
    write_text(output, "\n".join(lines) + "\n")

    return {
        "file": str(output),
        "data_file_count": len(files),
    }


def main() -> None:
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--workspace",
        required=True,
        type=Path,
        help="Workspace generated by iw_ingest_game_export.py",
    )

    parser.add_argument(
        "--project-root",
        required=True,
        type=Path,
        help="Repository root containing src/IdleWizard.BuildTool.Core",
    )

    args = parser.parse_args()

    workspace = args.workspace
    project_root = args.project_root

    engine_maps = workspace / "engine_maps"

    if not engine_maps.exists():
        raise SystemExit(
            f"Missing engine_maps folder: {engine_maps}. "
            f"Run iw_generate_engine_maps.py first."
        )

    out_dir = (
        project_root
        / "src"
        / "IdleWizard.BuildTool.Core"
        / "Generated"
    )

    reports_dir = workspace / "generated_reports"
    reports_dir.mkdir(parents=True, exist_ok=True)

    summary = {
        "effect_enum": generate_effect_enum(engine_maps, out_dir),
        "resource_catalog": generate_resource_catalog(engine_maps, out_dir),
        "data_file_catalog": generate_data_file_catalog(workspace, out_dir),
        "data_schemas": infer_data_schemas(workspace, reports_dir),
    }

    summary_path = reports_dir / "generation_summary.json"
    write_text(summary_path, json.dumps(summary, indent=2))

    print(f"Generated C# files into: {out_dir}")
    print(f"Generated reports into: {reports_dir}")
    print(f"Effect count: {summary['effect_enum']['effect_count']}")
    print(
        "Resource key candidates: "
        f"{summary['resource_catalog']['resource_key_candidate_count']}"
    )
    print(f"Data files: {summary['data_file_catalog']['data_file_count']}")
    print(
        "JSON parsed data files: "
        f"{summary['data_schemas']['json_parsed_count']}"
    )


if __name__ == "__main__":
    main()
